---
- name: create ticket with notes
  hosts: all
  gather_facts: no
  connection: local


  tasks:
  - name: include vars
    include_vars: incident_vars.yml


  - name: Create an incident
    snow_record:
      state: present
      table: cmdb_ci_linux_server
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
    register: new_host

  - debug: var=new_host.record
