---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:
  - name: include vars
    include_vars: incident_vars.yml
    
      
  - name: "gather_facts: yes"
    ios_facts:
      gather_subset: all


  - name: Create a network host record for "{{ inventory_hostname }}"
    snow_record:
      state: present
      table: cmdb_ci_netgear
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
        name: "{{ ansible_net_hostname }}"
        manufacturer: cisco
        model_number: "{{ ansible_net_model }}"
        assigned_to: "Abel Tuter"
        firmware_version: "{{ ansible_net_version }}"
        serial_number: "{{ ansible_net_serialnum }}"
        ip_address: "{{ inventory_hostname }}"
    register: new_host

#  - debug: var=new_host.record
  - debug: var=ansible_facts
