---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: show version
    ios_command:
      commands:
        - show version
    register: version

  - debug: var=new_host.record

  - name: parse show version
    command_parser:
      file: "parsers/show_version.yaml"
      content: "{{ version.stdout.0 }}"


  - name: Create an incident
    snow_record:
      state: present
      table: cmdb_ci_netgear
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
        manufacturer: cisco
    register: new_host

  - debug: var=new_host.record
